package docubase;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;


@RunWith(SpringRunner.class)
@SpringBootTest
public class LibraryTest {

    private static final String DOMAIN_URL = "nc.oliweb";

    @Autowired
    private Library myService;

    @Test
    public void contextLoads() {
        Assert.assertNotNull(myService.getUrlDomain());
        Assert.assertEquals(DOMAIN_URL, myService.getUrlDomain());
    }

    @SpringBootApplication
    static class TestConfiguration {
    }

}