package docubase;

import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.stereotype.Service;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Service
@ConditionalOnProperty(prefix = "opt.docubase", name = "url")
@EnableConfigurationProperties(DocubaseProperties.class)
public class Library {

    private final DocubaseProperties docubaseProperties;

    public Library(DocubaseProperties docubaseProperties) {
        this.docubaseProperties = docubaseProperties;
    }

    public String getUrlDomain() {
        return docubaseProperties.getUrl();
    }
}
